"""add equity_logs

Revision ID: 1709ea99703e
Revises: c7aad3f7c594
Create Date: 2026-04-16 16:46:04.528245

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1709ea99703e'
down_revision: Union[str, None] = 'c7aad3f7c594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('equity', sa.Numeric(), nullable=False),
    sa.Column('drawdown', sa.Numeric(), nullable=True),
    sa.Column('peak_balance', sa.Numeric(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_logs_account_id'), 'equity_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_equity_logs_id'), 'equity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_equity_logs_logged_at'), 'equity_logs', ['logged_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equity_logs_logged_at'), table_name='equity_logs')
    op.drop_index(op.f('ix_equity_logs_id'), table_name='equity_logs')
    op.drop_index(op.f('ix_equity_logs_account_id'), table_name='equity_logs')
    op.drop_table('equity_logs')
    # ### end Alembic commands ###
