"""initial schema

Revision ID: c7aad3f7c594
Revises: 
Create Date: 2026-04-16 15:29:07.167537

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c7aad3f7c594'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('account_size', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'support', 'sales', 'finance', 'risk_manager', 'account_manager', 'marketing', name='user_role'), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('phase', sa.Enum('phase1', 'phase2', 'funded', name='account_phase'), nullable=True),
    sa.Column('status', sa.Enum('active', 'passed', 'breached', 'funded', 'suspended', 'expired', name='account_status'), nullable=True),
    sa.Column('balance', sa.Numeric(), nullable=True),
    sa.Column('equity', sa.Numeric(), nullable=True),
    sa.Column('initial_balance', sa.Numeric(), nullable=False),
    sa.Column('peak_balance', sa.Numeric(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('risk_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('alert_type', sa.Enum('daily_loss', 'total_drawdown', 'trailing_drawdown', 'margin_call', 'lot_size', 'overexposure', 'news_trading', 'weekend_holding', 'profit_target', 'suspicious_activity', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alert_severity'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_triggered', sa.Numeric(), nullable=True),
    sa.Column('threshold', sa.Numeric(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'reviewed', 'resolved', 'escalated', 'dismissed', name='alert_status'), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_alerts_account_number'), 'risk_alerts', ['account_number'], unique=False)
    op.create_index(op.f('ix_risk_alerts_client_email'), 'risk_alerts', ['client_email'], unique=False)
    op.create_index(op.f('ix_risk_alerts_created_at'), 'risk_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_alerts_id'), 'risk_alerts', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('warning', 'breach', 'payout', 'system', 'info', name='notif_type'), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'paid', name='payout_status'), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_ref', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_id'), 'payouts', ['id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Numeric(), nullable=False),
    sa.Column('max_total_loss_pct', sa.Numeric(), nullable=False),
    sa.Column('profit_target_pct', sa.Numeric(), nullable=False),
    sa.Column('trailing_drawdown_pct', sa.Numeric(), nullable=True),
    sa.Column('max_lot_size', sa.Numeric(), nullable=True),
    sa.Column('max_open_lots', sa.Numeric(), nullable=True),
    sa.Column('max_open_trades', sa.Integer(), nullable=True),
    sa.Column('min_trading_days', sa.Integer(), nullable=True),
    sa.Column('news_trading_allowed', sa.Boolean(), nullable=True),
    sa.Column('weekend_holding_allowed', sa.Boolean(), nullable=True),
    sa.Column('ea_allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('broker_trade_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'SELL', name='trade_direction'), nullable=False),
    sa.Column('trade_type', sa.Enum('market', 'limit', 'stop', name='trade_type'), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'cancelled', name='trade_status'), nullable=True),
    sa.Column('lot', sa.Numeric(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('exit_price', sa.Numeric(), nullable=True),
    sa.Column('stop_loss', sa.Numeric(), nullable=True),
    sa.Column('take_profit', sa.Numeric(), nullable=True),
    sa.Column('commission', sa.Numeric(), nullable=True),
    sa.Column('swap', sa.Numeric(), nullable=True),
    sa.Column('gross_profit', sa.Numeric(), nullable=True),
    sa.Column('open_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('violation_type', sa.Enum('daily_loss', 'total_loss', 'lot_size', 'trailing_drawdown', 'news_trading', 'weekend_holding', 'open_trades_limit', name='violation_type'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value_at_breach', sa.Numeric(), nullable=True),
    sa.Column('rule_limit', sa.Numeric(), nullable=True),
    sa.Column('breached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_id'), 'violations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_id'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_payouts_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_risk_alerts_id'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_created_at'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_client_email'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_account_number'), table_name='risk_alerts')
    op.drop_table('risk_alerts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
